App\Entity\Category:
  attributes:
    id:
      groups: ['category_read', 'expense_read']
    name:
      groups: ['category_read', 'category_post', 'category_put', 'expense_read']
    user:
      groups: ['category_read', 'category_post']
    group:
      groups: ['category_read', 'category_post']
    createdAt:
      groups: ['category_read']
    updatedAt:
      groups: ['category_read']